{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": None,
   "id": "fa7742f3-6934-4baf-a267-bc1a021b2cf3",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "import joblib\n",
    "import shap\n",
    "import matplotlib.pyplot as plt\n",
    "from io import BytesIO\n",
    "\n",
    "# 页面设置\n",
    "st.set_page_config(\n",
    "    page_title=\"IDH突变预测系统 (AdaBoost)\",\n",
    "    layout=\"wide\",\n",
    "    initial_sidebar_state=\"expanded\"\n",
    ")\n",
    "\n",
    "# 加载模型和示例数据\n",
    "@st.cache_resource\n",
    "def load_model():\n",
    "    return joblib.load('RF.pkl')  # 替换为您的模型路径\n",
    "\n",
    "model = load_model()\n",
    "\n",
    "# SHAP解释器初始化\n",
    "@st.cache_resource\n",
    "def init_shap():\n",
    "    explainer = shap.TreeExplainer(model)  # 适配AdaBoost模型\n",
    "    return explainer\n",
    "\n",
    "explainer = init_shap()\n",
    "\n",
    "# 用户输入界面\n",
    "st.title('🧠 IDH突变概率预测系统')\n",
    "st.markdown(\"\"\"\n",
    "基于AdaBoost模型预测脑胶质瘤IDH突变状态，提供SHAP可解释性分析  \n",
    "*注：所有输入数据仅用于实时计算，不会被存储*\n",
    "\"\"\")\n",
    "\n",
    "# 侧边栏 - 输入参数\n",
    "st.sidebar.header('影像特征输入')\n",
    "\n",
    "# 动态生成输入字段\n",
    "input_data = {}\n",
    "cols = st.columns(2)\n",
    "features = ['age', 'diameter', 'SII', 'enhanced', 'FPR', 'lobe', 'symptom', 'edema']\n",
    "\n",
    "with cols[0]:\n",
    "    input_data['age'] = st.number_input(\"年龄（岁）\", min_value=0, max_value=100, value=45)\n",
    "    input_data['diameter'] = st.number_input(\"肿瘤直径（mm）\", min_value=0.0, max_value=200.0, value=30.0)\n",
    "    input_data['SII'] = st.number_input(\"SII指数\", min_value=0.0, max_value=2000.0, value=600.0)\n",
    "    input_data['enhanced'] = st.selectbox(\"强化程度\", options=[\"无强化\", \"轻度强化\", \"明显强化\"], index=1)\n",
    "\n",
    "with cols[1]:\n",
    "    input_data['FPR'] = st.number_input(\"FPR值\", min_value=0.0, max_value=2.0, value=0.5, step=0.1)\n",
    "    input_data['lobe'] = st.selectbox(\"脑叶位置\", options=[\"额叶\", \"颞叶\", \"顶叶\", \"枕叶\", \"多脑叶\"], index=0)\n",
    "    input_data['symptom'] = st.selectbox(\"临床症状\", options=[\"无症状\", \"头痛\", \"癫痫\", \"神经功能障碍\"], index=1)\n",
    "    input_data['edema'] = st.selectbox(\"瘤周水肿\", options=[\"无\", \"轻度\", \"中度\", \"重度\"], index=1)\n",
    "\n",
    "# 预处理函数\n",
    "def preprocess_input(input_dict):\n",
    "    # 转换分类变量\n",
    "    enhanced_map = {\"无强化\":0, \"轻度强化\":1, \"明显强化\":2}\n",
    "    lobe_map = {\"额叶\":0, \"颞叶\":1, \"顶叶\":2, \"枕叶\":3, \"多脑叶\":4}\n",
    "    symptom_map = {\"无症状\":0, \"头痛\":1, \"癫痫\":2, \"神经功能障碍\":3}\n",
    "    edema_map = {\"无\":0, \"轻度\":1, \"中度\":2, \"重度\":3}\n",
    "    \n",
    "    processed = {\n",
    "        'age': input_dict['age'],\n",
    "        'diameter': input_dict['diameter'],\n",
    "        'SII': input_dict['SII'],\n",
    "        'enhanced': enhanced_map[input_dict['enhanced']],\n",
    "        'FPR': input_dict['FPR'],\n",
    "        'lobe': lobe_map[input_dict['lobe']],\n",
    "        'symptom': symptom_map[input_dict['symptom']],\n",
    "        'edema': edema_map[input_dict['edema']]\n",
    "    }\n",
    "    return pd.DataFrame([processed])\n",
    "\n",
    "# 预测按钮\n",
    "if st.button('预测IDH突变概率'):\n",
    "    # 转换为DataFrame并预处理\n",
    "    input_df = preprocess_input(input_data)\n",
    "    \n",
    "    # 预测\n",
    "    proba = model.predict_proba(input_df)[0][1]\n",
    "    prediction = \"突变型\" if proba >= 0.5 else \"野生型\"\n",
    "    \n",
    "    # 结果显示\n",
    "    st.success(f\"\"\"\n",
    "    ### 预测结果\n",
    "    - **IDH突变概率**: {proba:.1%}  \n",
    "    - **预测类型**: {prediction}\n",
    "    - **临床意义**: {'建议结合分子检测确认' if prediction == \"突变型\" else '需考虑其他治疗方案'}\n",
    "    \"\"\")\n",
    "    \n",
    "    # SHAP解释\n",
    "    st.divider()\n",
    "    st.subheader(\"模型决策解释 (SHAP)\")\n",
    "    \n",
    "    # 计算SHAP值\n",
    "    shap_values = explainer.shap_values(input_df)\n",
    "    \n",
    "    # 全局解释\n",
    "    with st.expander(\"📊 特征重要性分析\", expanded=True):\n",
    "        fig1, ax1 = plt.subplots(figsize=(10, 6))\n",
    "        shap.summary_plot(shap_values, input_df, plot_type=\"bar\", show=False)\n",
    "        st.pyplot(fig1)\n",
    "        st.caption(\"各特征对预测结果的总体影响（绝对值平均）\")\n",
    "    \n",
    "    # 个体解释\n",
    "    with st.expander(\"🔍 个体预测分解\", expanded=True):\n",
    "        fig2 = plt.figure()\n",
    "        shap.force_plot(\n",
    "            explainer.expected_value[1],  # 正类期望值\n",
    "            shap_values[1], \n",
    "            input_df.iloc[0],\n",
    "            matplotlib=True,\n",
    "            show=False\n",
    "        )\n",
    "        st.pyplot(fig2)\n",
    "        st.caption(\"红色特征增加突变概率，蓝色特征降低概率\")\n",
    "\n",
    "    # 特征依赖分析\n",
    "    st.subheader(\"关键特征分析\")\n",
    "    selected_feat = st.selectbox(\"选择特征查看详细影响\", features)\n",
    "    fig3, ax3 = plt.subplots(figsize=(10, 6))\n",
    "    shap.dependence_plot(\n",
    "        selected_feat,\n",
    "        shap_values[1], \n",
    "        input_df,\n",
    "        interaction_index=None,\n",
    "        show=False\n",
    "    )\n",
    "    st.pyplot(fig3)\n",
    "\n",
    "# 示例数据加载\n",
    "with st.sidebar.expander(\"💡 使用示例病例\"):\n",
    "    if st.button(\"加载典型突变型病例\"):\n",
    "        st.session_state.age = 38\n",
    "        st.session_state.diameter = 28.5\n",
    "        st.session_state.SII = 720\n",
    "        st.session_state.enhanced = \"轻度强化\"\n",
    "        st.session_state.FPR = 0.4\n",
    "        st.session_state.lobe = \"额叶\"\n",
    "        st.session_state.symptom = \"癫痫\"\n",
    "        st.session_state.edema = \"轻度\"\n",
    "        st.rerun()\n",
    "    \n",
    "    if st.button(\"加载典型野生型病例\"):\n",
    "        st.session_state.age = 62\n",
    "        st.session_state.diameter = 45.0\n",
    "        st.session_state.SII = 980\n",
    "        st.session_state.enhanced = \"明显强化\"\n",
    "        st.session_state.FPR = 0.8\n",
    "        st.session_state.lobe = \"多脑叶\"\n",
    "        st.session_state.symptom = \"神经功能障碍\"\n",
    "        st.session_state.edema = \"中度\"\n",
    "        st.rerun()\n",
    "\n",
    "# 临床指南\n",
    "with st.expander(\"ℹ️ IDH临床意义指南\"):\n",
    "    st.markdown(\"\"\"\n",
    "    **IDH突变型胶质瘤特征** :\n",
    "    1. 患者年龄通常<50岁\n",
    "    2. MRI常见T2-FLAIR错配征\n",
    "    3. 强化程度多较轻\n",
    "    4. 预后优于野生型\n",
    "    \n",
    "    **治疗决策参考**:\n",
    "    - 突变型：考虑IDH抑制剂靶向治疗\n",
    "    - 野生型：优先放化疗联合方案\n",
    "    \"\"\")\n",
    "\n",
    "# 部署说明\n",
    "st.sidebar.markdown(\"\"\"\n",
    "**系统要求**:\n",
    "- Python 3.8+\n",
    "- 依赖库: `streamlit shap matplotlib pandas numpy joblib`\n",
    "- 模型文件: `RF.pkl` (需放在同级目录)\n",
    "\"\"\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "ml",
   "language": "python",
   "name": "ml"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
